displayName=Gem Sack
author=serenibyss
description=Extra info at a glance about the Gem Sack (and its earlier forms)
tags=gem,sack,crafting,sapphire,emerald,ruby,diamond,dragonstone,opal,jade,topaz
version=1.2
plugins=io.github.serenibyss.gemsack.GemSackPlugin
build=standard
